language: node_js

node_js:
  - "8"
  - "7"
  - "6"

stages:
  - system_and_integration
  - functional
  - code_quality
  - security

install:
  - npm install -g bower
  - yarn install
  - bower install

jobs:
  include:
    - stage: system_and_integration
      script:
        - npm run mocha
    - stage: functional
      script:
        - npm run karma
    - stage: code_quality
      script:
        - npm run eslint
    - stage: security_checks
      script:
        - npm run nsp
