# tmpl8-react : docker deployment [dev]
# -------------------------------------
# This file deploys the application in development mode using a container architecture.
#
# reference: https://docs.docker.com/compose/compose-file/
version: "3"
services:
  tmpl8_react_dev:
    build: .
    dns:
      - "8.8.8.8"
    deploy:
      labels:
        com.tmpl8_react.description: "Template React application"
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: ./scripts/docker-entrypoint.dev.sh
    environment:
      - LOG_PATH=/app/logs
      - NODE_ENV=dev
      - PORT=3333
    ports:
      - "3333:3333"
    expose: 
      - "3333"